# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a625709e7006a9a5ecb328e6b6105149362232e8b1bd3a00925d93944510e683356c142119d6a58bef6a607872d1f0edb87abcafe26ef0ec605385b677c43acd

test:
  secret_key_base: 60a3f4e1d764d1a00115345ea99bf1cdf405715721df6cb8892db4b4aaac27028af758c21195f1b081bcddbf5dac85b5c660e1cf8ab5c65ed7cf801e815e0e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
